9. View Component/9. View Component/Models/Person.cs
namespace _9._View_Component.Models
{
    public class Person
    {
        public string? PersonName { get; set; }
        public string? JobTitle {  get; set; }
    }
}

9. View Component/9. View Component/Models/PersonGrid.cs
namespace _9._View_Component.Models
{
    public class PersonGrid
    {
        public string GridTitle { get; set; }
        public List<Person> Persons {  get; set; } = new List<Person>();
    }
}

9. View Component/9. View Component/Controllers/HomeController.cs
using _9._View_Component.Models;
using Microsoft.AspNetCore.Mvc;

namespace _9._View_Component.Controllers
{
    public class HomeController : Controller
    {
        [Route("/")]
        public IActionResult Index()
        {
            return View();
        }

        [Route("/about")]
        public IActionResult About()
        {
            return View();
        }

        [Route("/load-friends-list")]
        public IActionResult Friends()
        {
            PersonGrid PersonGrid = new PersonGrid()
            {
                GridTitle = "Persons List",
                Persons = new List<Person>
                {
                    new Person()
                    {
                        PersonName = "John Wick",
                        JobTitle = "Professional Killer"
                    },
                      new Person()
                    {
                        PersonName = "Uchiha Obito",
                        JobTitle = "Hokage"
                    }
                }
            };
            return ViewComponent("Grid", new
            {
                grid  = PersonGrid
            });
        }
    }
}

9. View Component/9. View Component/ViewComponents/GridViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using _9._View_Component.Models;

namespace _9._View_Component.ViewComponents
{
    [ViewComponent] //Either this or suffix class with ViewComponent 
    public class GridViewComponent : ViewComponent
    {
        public async Task<IViewComponentResult> InvokeAsync(PersonGrid grid)
        {
            /*PersonGrid PersonGrid = new PersonGrid()
            {
                GridTitle = "Persons List",
                Persons = new List<Person>
                {
                    new Person()
                    {
                        PersonName = "John Wick",
                        JobTitle = "Professional Killer"
                    },
                      new Person()
                    {
                        PersonName = "Uchiha Obito",
                        JobTitle = "Hokage"
                    }
                }
            };
            ViewData["Grid"] = PersonGrid;*/
            return View(grid);  //Not a regular view but a partial view location: Views/Shared/ViewComponent/Grid/Default.cshtml
        }
    }
}

9. View Component/9. View Component/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>About</h1>

@* @await Component.InvokeAsync("Grid") *@

@* <vc:grid></vc:grid> *@

@{
    PersonGrid personGridModel = new PersonGrid()
            {
                GridTitle = "Friends",
                Persons = new List<Person>()
                {
                    new Person(){
                        PersonName = "Sahil Kawade",
                        JobTitle = "Backend Architect"
                    },
                     new Person(){
                        PersonName = "Shubham Raut",
                        JobTitle = "QA/Product Lead"
                    }
                }
            };
}

@await Component.InvokeAsync("Grid", new {
    grid = personGridModel
})

9. View Component/9. View Component/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home";
}
<h1>Home</h1>

@* @{
    PersonGrid personGridModel = new PersonGrid()
            {
                GridTitle = "Persons",
                Persons = new List<Person>()
                {
                    new Person(){
                        PersonName = "Sahil Kawade",
                        JobTitle = "Backend Architect"
                    },
                     new Person(){
                        PersonName = "Shubham Raut",
                        JobTitle = "QA/Product Lead"
                    }
                }
            };
}

@await Component.InvokeAsync("Grid", new {
    grid = personGridModel
}) *@

<button class="btn btn-primary" id="load-view-component">Load</button>
<div class="showOutput"></div>

<script>
    const loadBtn = document.getElementById("load-view-component");
    const targetOutput = document.querySelector(".showOutput");
    loadBtn.addEventListener("click", async () => {
        const response = await fetch("load-friends-list");
        const data = await response.text();
        targetOutput.innerHTML = data;
    });
</script>

9. View Component/9. View Component/Views/Shared/Components/Grid/Default.cshtml
@model PersonGrid
<h5>@Model.GridTitle</h5>
<table class="table">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Job Title</th>
        </tr>
    </thead>
    <tbody>
        @foreach(Person person in Model.Persons)
        {   
        <tr>
            <td>@person.PersonName</td>
            <td>@person.JobTitle</td>
        </tr>
        }
    </tbody>
</table>