16.ContactsManager.Solution/16.ContactsManager.UI/Controllers/HomeController.cs
using Microsoft.AspNetCore.Diagnostics;
using Microsoft.AspNetCore.Mvc;

namespace Controllers
{
    public class HomeController : Controller
    {
        [Route("Error")]
        public IActionResult Error()
        {
            IExceptionHandlerPathFeature? exceptionHandler = HttpContext.Features.Get<IExceptionHandlerPathFeature>();
            if(exceptionHandler != null && exceptionHandler.Error != null)
            {
                ViewBag.ErrorMessage = exceptionHandler.Error.Message;
            }
            return View(); //Views / Shared/ Error
        }
    }
}

16.ContactsManager.Solution/16.ContactsManager.UI/Controllers/PersonsController.cs
using Microsoft.AspNetCore.Mvc;
using Rotativa.AspNetCore;
using System.Reflection;
using Services;
using ServiceContracts;
using Filters.ActionFilters;
using _16.ContactsManger.Core.Domain.Entities;
using Filters.ResourceFilters;

namespace Controllers
{
    //[TypeFilter(typeof(ResponseHeaderActionFilter), Arguments = new object[] { "my-controller-key", "my-controller-value", 3 })]  //Class level filter
 //   [TypeFilter(typeof(TokenResultFilter))]
  //  [TypeFilter(typeof(HandleExceptionFilter))]
  //  [TypeFilter(typeof(PersonsAlwaysRunResultFilter))]
  //  [SkipFilter]
    public class PersonsController : Controller
    {
        private readonly IPersonAdderService _personAdderService;
        private readonly IPersonGetterService _personGetterService;

        public PersonsController(IPersonAdderService personAdderService, IPersonGetterService personGetterService)
        {
            _personAdderService = personAdderService;
            _personGetterService = personGetterService; 
        }

        [Route("/")]
        // [TypeFilter(typeof(ResponseHeaderActionFilter), Arguments = new object[] { "my-action-key", "my-action-value", 1 })]   // Arguments for action filter and Reusable (parameterized) filter  and action level filter
        //[ServiceFilter(typeof(PersonsListResultFilter))]
        [ResponseHeaderActionFilter("my-action-key", "my-action-value", 1)]
        public async Task<IActionResult> Index()
        {
            List<Person> persons = await _personGetterService.GetPersons();
            return View(persons);
        }

        [Route("[action]")]
        [HttpPost]
        [TypeFilter(typeof(FeaturesDisabledResourceFilter))]
        public async Task<IActionResult> CreatePerson(Person person)
        {
            await _personAdderService.AddPersonToDb(person);
            return RedirectToAction("Index");
        }

        [Route("create/person")]
        public IActionResult CreatePersonForm()
        {
            return View();
        }

        [Route("[action]/{Id}")]
        //[TypeFilter(typeof(PersonsListActionFilter))] //This will create an object of personslistactionfilter and attach it to this action
       // [TypeFilter(typeof(TokenAutorizationFilter))]
        public async Task<IActionResult> EditPerson(int Id)
        {
            if (Id == null)
            {
                return Content("Person cannot be null");
            }
            Person p1 = await _personGetterService.GetPersonById(Id);
            return View(p1);
        }

        [Route("PersonsPDF")]
        public async Task<IActionResult> PersonsPDF()
        {
            //Get list of persons
            List<Person> persons = await _personGetterService.GetPersons();
            return new ViewAsPdf("PersonsPDF", persons, ViewData)
            {
                PageMargins = new Rotativa.AspNetCore.Options.Margins()
                {
                    Top = 20,
                    Right = 20,
                    Bottom = 20,
                    Left = 20
                },
                PageOrientation = Rotativa.AspNetCore.Options.Orientation.Landscape
            };
        }
    }
}

16.ContactsManager.Solution/16.ContactsManager.UI/Views/Persons/CreatePersonForm.cshtml
@model Person
<form asp-controller="Persons" asp-action="CreatePerson" method="post">
    <div class="row">
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="col-md-6">
                <label asp-for="Age"></label>
                <input asp-for="Age" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="JobTitle"></label>
                <input asp-for="JobTitle" class="form-control" />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Update</button>
</form>

16.ContactsManager.Solution/16.ContactsManager.UI/Views/Persons/EditPerson.cshtml
@model Person
<form asp-controller="Persons" asp-action="UpdatePerson" method="post">
    <div class="row">
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="Id"></label>
                <input asp-for="Id" class="form-control" disabled />
            </div>
            <div class="col-md-6">
                <label asp-for="Name"></label>
                <input asp-for="Name" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="Email"></label>
                <input asp-for="Email" class="form-control" />
            </div>
            <div class="col-md-6">
                <label asp-for="Age"></label>
                <input asp-for="Age" class="form-control" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-6">
                <label asp-for="BirthDate"></label>
                <input asp-for="BirthDate" class="form-control" />
            </div>
        </div>
    </div>
    <button type="submit" class="btn btn-primary mt-3">Update</button>
</form>

16.ContactsManager.Solution/16.ContactsManager.UI/Views/Persons/Index.cshtml
@model IEnumerable<Person>
@{
    ViewBag.Title = "Persons";
}

<a class="btn btn-primary mb-3 mt-2" asp-controller="Persons" asp-action="PersonsPDF">Get PDF</a>
<a class="btn btn-primary mb-3 mt-2" asp-controller="Persons" asp-action="PersonsCSV">Get CSV</a>
<a class="btn btn-primary mb-3 mt-2" asp-controller="Persons" asp-action="PersonsExcel">Get Excel</a>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Job Title</th>
            <th>Age</th>
            <th>Date of Birth</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Person person in Model)
        {
            <tr>
                <td>@person.Id</td>
                <td>@person.Name</td>
                <td>@person.Email</td>
                <td>@person.JobTitle</td>
                <td>@person.Age</td>
                <td>@person.BirthDate.ToString("dd/MMM/yyyy").Replace("-","/") </td>
                <td>
                    <a class="btn btn-primary" asp-controller="Persons" asp-action="EditPerson" asp-route-Id="@person.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>

16.ContactsManager.Solution/16.ContactsManager.UI/Views/Persons/PersonsPDF.cshtml
@model IEnumerable<Person>
@{
    Layout = null;
}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Job Title</th>
            <th>Age</th>
            <th>Date of Birth</th>
            <th>&nbsp;</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Person person in Model)
        {
            <tr>
                <td>@person.Id</td>
                <td>@person.Name</td>
                <td>@person.Email</td>
                <td>@person.JobTitle</td>
                <td>@person.Age</td>
                <td>@person.BirthDate.ToString("dd/MMM/yyyy").Replace("-","/") </td>
                <td>
                    <a class="btn btn-primary" asp-controller="Persons" asp-action="EditPerson" asp-route-Id="@person.Id">Edit</a>
                </td>
            </tr>
        }
    </tbody>
</table>